export const keysDescription = {
    "Row ID":"A unique identifier for each row in the dataset.",
    "Transaction ID": "A unique identifier for each transaction or sale.",
    "Date": "The date on which the transaction occurred.",
    "Ship Date": "The date when the order was shipped.",
    "Ship Mode": "The mode of shipping used (e.g., standard, expedited).",
    "Time": "The time at which the transaction occurred.",
    "Customer ID": "A unique identifier for each customer.",
    "Customer Name": "The name of the customer.", 
    "Customer Age": "The age of the customer.",
    "Customer Gender": "The gender of the customer.",
    "Product ID": "A unique identifier for each product.",
    "Product Name":"The name or description of the product.",
    "Category": "The category to which the product belongs (e.g., electronics, clothing, groceries).",
    "Sub-Category": "The sub-category of the product.",
    "Quantity": "The number of units of the product sold in the transaction.",
    "Unit Price": "The price per unit of the product.",
    "Total Price": "The total price for the quantity of products sold in the transaction (Quantity * Unit Price).",
    "Payment Method": "The method of payment used (e.g., cash, credit card, debit card).",
    "Store Location": "The location of the store where the transaction took place.",
    "Discount": "Any discount applied to the transaction.",
    "Salesperson ID": "A unique identifier for the salesperson handling the transaction.",
    "Profit Margin": "The profit margin on the product sold.",
    "Description": "A detailed summary or information about the product or transaction.",
    "Segment": "The customer segment.",
    "Country": "The country where the transaction was shipped.",
    "City": "The city where the transaction was shipped.",
    "State": "The state or province where the transaction was shipped.",
    "Postal Code":"The postal or ZIP code of the shipping address.",
    "Region": "The geographical region where the transaction was shipped.",
    "Profit": "The net earnings from a sale after subtracting costs.",
    "Other": "Other",
};
export const option = [
    {value: "Row ID", label: "Row ID"},
    {value: "Transaction ID", label: "Transaction ID"},
    {value: "Date", label: "Date"},
    {value: "Ship Date", label: "Ship Date"},
    {value: "Ship Mode", label: "Ship Mode"},
    {value: "Time", label: "Time"},
    {value: "Customer ID", label: "Customer ID"},
    {value: "Customer Name", label: "Customer Name"},
    {value: "Product ID", label: "Product ID"},
    {value: "Product Name", label: "Product Name"},
    {value: "Category", label: "Category"},
    {value: "Sub-Category", label: "Sub-Category"},
    {value: "Quantity", label: "Quantity"},
    {value: "Unit Price", label: "Unit Price"},
    {value: "Total Price", label: "Total Price"},
    {value: "Payment Method", label: "Payment Method"},
    {value: "Store Location", label: "Store Location"},
    {value: "Discount", label: "Discount"},
    {value: "Salesperson ID", label: "Salesperson ID"},
    {value: "Profit Margin", label: "Profit Margin"},
    {value: "Description", label: "Description"},
    {value: "Segment", label: "Segment"},
    {value: "Country", label: "Country"},
    {value: "City", label: "City"},
    {value: "State", label: "State"},
    {value: "Postal Code", label: "Postal Code"},
    {value: "Region", label: "Region"},
    {value: "Profit", label: "Profit"},
    {value: "Other", label: "Other"},
  ];

export const keysApi = {
    "Row ID":"include",
    "Transaction ID": "include",
    "Date": "daterange",
    "Time": "range",
    "Customer ID": "include",
    "Customer Name": "include", 
    "Customer Age": "range",
    "Customer Gender": "include",
    "Product ID": "include",
    "Product Name":"include",
    "Category": "include",
    "Sub-Category": "include",
    "Quantity": "range",
    "Unit Price": "range",
    "Total Price": "range",
    "Payment Method": "include",
    "Store Location": "include",
    "Discount": "include",
    "Salesperson ID": "include",
    "Profit Margin": "range",
    "Description": "include",
    "Segment": "include",
    "Country": "include",
    "City": "include",
    "State": "include",
    "Postal Code":"include",
    "Region": "include",
    "Profit": "range",
    "Other": "Other",
};
export const sampleFields = ['Quantity', 'Total Price', 'Unit Price','Profit']
export const rfmClassification = [
    {
        name:'Champions',
        color:'rgb(75, 192, 192)',
    },
    {
        name:'Loyal Customers',
        color:'rgb(54, 162, 235)',
    },
    {
        name:'Potential Loyalist',
        color:'#55b685',
    },
    {
        name:'New Customers',
        color:'rgb(153, 102, 255)',
    },
    {
        name:'Promising',
        color:'rgb(255, 159, 64)',
    },
    {
        name:'Need Attention',
        color:'#e87b35',
    },
    {
        name:'About To Sleep',
        color:'rgb(124, 70, 74)',
    },
    {
        name:'At Risk',
        color:'rgb(255, 99, 132)',
    },
    {
        name:"Can't Lose Them",
        color:'rgb(255, 205, 86)',
    },
    {
        name:'Hibernating',
        color:'#a8b4f6',
    },
];

export const QAndA = [
    {quest: "Why is the website not displaying correctly on my device?", answer: "This may occur if the website isn’t optimized for your device or browser, especially if it involves complex charts and graphs. Try updating your browser or switching to a different one. Some data analysis websites have specific browser requirements, so check their recommendations for the best experience."},
    {quest: "Why is the website slow to load my data?", answer: "The website may be slow due to large datasets being processed, server overload, or poor internet connectivity. It could also be that the website is running complex algorithms or visualizations that require more resources. Try clearing your browser cache, using a wired connection, or waiting for off-peak hours."},
    {quest: "Why can't I find the specific data or tool I'm looking for on the data analysis website?", answer: "Data analysis websites often have many layers of tools and information. Use the search function to locate specific datasets or analysis tools. If you're still having trouble, explore the help section or user guides to navigate the interface more efficiently."},
    {quest: "What file formats are supported for uploading?", answer: "Our platform supports the following file formats: CSV and Excel (.xlsx). Ensure that your file is formatted correctly to avoid upload errors."},
    {quest: "Can I perform real-time analysis with live data?", answer: "No, our platform currently does not support real-time analysis with live data. At this time, only static data files can be uploaded and analyzed. We are working on implementing live data integration features in the future to support real-time analysis. Stay tuned for updates!"},
    {quest: "How secure is my data?", answer: "Your data is securely stored using PostgreSQL with SSL encryption and role-based access control for database security. Files are stored in MINIO with end-to-end encryption and strict access policies, ensuring both in-transit and at-rest data protection."},
    {quest: "How do I clean missing or null values in my dataset?", answer: "You don't need to worry about cleaning missing or null values—our platform automatically detects and removes them for you during the data upload process. This ensures that your analysis runs smoothly without incomplete records."},
    // {quest: "", answer: ""},
]